
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action quitAction;
	
	private global::Gtk.Action NovoMundoAction;
	
	private global::Gtk.Action refreshAction;
	
	private global::Gtk.Action QuitAction;
	
	private global::Gtk.Action clearAction;
	
	private global::Gtk.Action AboutAction;
	
	private global::Gtk.Action HelpAction;
	
	private global::Gtk.ToggleAction queryAction;
	
	private global::Gtk.Action StarButton;
	
	private global::Gtk.ToggleAction mediaPauseAction;
	
	private global::Gtk.Action zoomInAction;
	
	private global::Gtk.Action zoomOutAction;
	
	private global::Gtk.Action quitAction1;
	
	private global::Gtk.ToggleAction findAction;
	
	private global::Gtk.Action refreshAction1;
	
	private global::Gtk.ToggleAction PresButanToGoction;
	
	private global::Gtk.Action SpeedUpSimulation;
	
	private global::Gtk.Action SlowDownSimulation;
	
	private global::Gtk.Action infoAction;
	
	private global::Gtk.VPaned vpaned1;
	
	private global::Gtk.VBox vbox8;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Button EarthButton;
	
	private global::Gtk.Toolbar toolbar5;
	
	private global::Gtk.VSeparator vseparator1;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.HBox hbox7;
	
	private global::Gtk.HBox hbox6;
	
	private global::Gtk.HBox hbox9;
	
	private global::Gtk.HBox hbox12;
	
	private global::Gtk.Image image9;
	
	private global::Gtk.TextView textview1;
	
	private global::Gtk.HBox hbox11;
	
	private global::Gtk.Image image10;
	
	private global::Gtk.TextView textview2;
	
	private global::Gtk.HBox hbox8;
	
	private global::Gtk.HBox hbox10;
	
	private global::Gtk.Image image11;
	
	private global::Gtk.TextView textview3;
	
	private global::Gtk.HBox hbox13;
	
	private global::Gtk.Image image12;
	
	private global::Gtk.TextView textview4;
	
	private global::Gtk.VSeparator vseparator2;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Toolbar toolbar1;
	
	private global::Gtk.Statusbar TimeStatusBar;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView OutputBox;
	
	private global::Gtk.VBox vbox9;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.EventBox TileMapEventBox;
	
	private global::Gtk.Image TileMap;
	
	private global::Gtk.Statusbar StatusBar;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.quitAction = new global::Gtk.Action ("quitAction", null, null, "gtk-quit");
		w1.Add (this.quitAction, "<Mod2>F4");
		this.NovoMundoAction = new global::Gtk.Action ("NovoMundoAction", global::Mono.Unix.Catalog.GetString ("NovoMundo"), null, null);
		this.NovoMundoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("NovoMundo");
		w1.Add (this.NovoMundoAction, "<Mod2>n");
		this.refreshAction = new global::Gtk.Action ("refreshAction", null, null, "gtk-refresh");
		w1.Add (this.refreshAction, null);
		this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, null);
		this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.QuitAction, "<Mod2>F4");
		this.clearAction = new global::Gtk.Action ("clearAction", null, null, "gtk-clear");
		w1.Add (this.clearAction, "<Mod2>c");
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.queryAction = new global::Gtk.ToggleAction ("queryAction", null, null, "gtk-find");
		w1.Add (this.queryAction, null);
		this.StarButton = new global::Gtk.Action ("StarButton", null, null, "gtk-about");
		w1.Add (this.StarButton, "p");
		this.mediaPauseAction = new global::Gtk.ToggleAction ("mediaPauseAction", null, null, "gtk-media-pause");
		w1.Add (this.mediaPauseAction, null);
		this.zoomInAction = new global::Gtk.Action ("zoomInAction", null, null, "gtk-zoom-in");
		w1.Add (this.zoomInAction, null);
		this.zoomOutAction = new global::Gtk.Action ("zoomOutAction", null, null, "gtk-zoom-out");
		w1.Add (this.zoomOutAction, null);
		this.quitAction1 = new global::Gtk.Action ("quitAction1", null, null, "gtk-quit");
		w1.Add (this.quitAction1, null);
		this.findAction = new global::Gtk.ToggleAction ("findAction", null, null, "gtk-find");
		w1.Add (this.findAction, null);
		this.refreshAction1 = new global::Gtk.Action ("refreshAction1", null, null, "gtk-refresh");
		w1.Add (this.refreshAction1, null);
		this.PresButanToGoction = new global::Gtk.ToggleAction ("PresButanToGoction", null, null, "gtk-go-forward");
		w1.Add (this.PresButanToGoction, null);
		this.SpeedUpSimulation = new global::Gtk.Action ("SpeedUpSimulation", null, null, "gtk-zoom-in");
		w1.Add (this.SpeedUpSimulation, null);
		this.SlowDownSimulation = new global::Gtk.Action ("SlowDownSimulation", null, null, "gtk-zoom-out");
		w1.Add (this.SlowDownSimulation, null);
		this.infoAction = new global::Gtk.Action ("infoAction", null, null, "gtk-info");
		w1.Add (this.infoAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("NovoMundo");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "stock_internet", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vpaned1 = new global::Gtk.VPaned ();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 115;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.EarthButton = new global::Gtk.Button ();
		this.EarthButton.WidthRequest = 50;
		this.EarthButton.HeightRequest = 50;
		this.EarthButton.CanFocus = true;
		this.EarthButton.Name = "EarthButton";
		this.EarthButton.UseUnderline = true;
		this.EarthButton.FocusOnClick = false;
		global::Gtk.Image w2 = new global::Gtk.Image ();
		w2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("NovoMundo.graphics.icons.globe.png");
		this.EarthButton.Image = w2;
		this.hbox4.Add (this.EarthButton);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.EarthButton]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		w3.Padding = ((uint)(5));
		// Container child hbox4.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar5'><toolitem name='quitAction1' action='quitAction1'/><toolitem name='findAction' action='findAction'/><toolitem name='refreshAction1' action='refreshAction1'/><toolitem name='infoAction' action='infoAction'/></toolbar></ui>");
		this.toolbar5 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar5")));
		this.toolbar5.Name = "toolbar5";
		this.toolbar5.ShowArrow = false;
		this.hbox4.Add (this.toolbar5);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.toolbar5]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vseparator1 = new global::Gtk.VSeparator ();
		this.vseparator1.Name = "vseparator1";
		this.hbox4.Add (this.vseparator1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vseparator1]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox ();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.image9 = new global::Gtk.Image ();
		this.image9.Name = "image9";
		this.image9.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("NovoMundo.graphics.icons.energy.png");
		this.hbox12.Add (this.image9);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.image9]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.textview1 = new global::Gtk.TextView ();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.textview1.Editable = false;
		this.textview1.CursorVisible = false;
		this.textview1.AcceptsTab = false;
		this.hbox12.Add (this.textview1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.textview1]));
		w7.Position = 1;
		this.hbox9.Add (this.hbox12);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.hbox12]));
		w8.Position = 0;
		// Container child hbox9.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox ();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.image10 = new global::Gtk.Image ();
		this.image10.Name = "image10";
		this.image10.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("NovoMundo.graphics.icons.nous.png");
		this.hbox11.Add (this.image10);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.image10]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox11.Gtk.Box+BoxChild
		this.textview2 = new global::Gtk.TextView ();
		this.textview2.CanFocus = true;
		this.textview2.Name = "textview2";
		this.textview2.Editable = false;
		this.textview2.CursorVisible = false;
		this.textview2.AcceptsTab = false;
		this.hbox11.Add (this.textview2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.textview2]));
		w10.Position = 1;
		this.hbox9.Add (this.hbox11);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.hbox11]));
		w11.Position = 1;
		this.hbox6.Add (this.hbox9);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.hbox9]));
		w12.Position = 0;
		// Container child hbox6.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.image11 = new global::Gtk.Image ();
		this.image11.Name = "image11";
		this.image11.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("NovoMundo.graphics.icons.dna.png");
		this.hbox10.Add (this.image11);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.image11]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.textview3 = new global::Gtk.TextView ();
		this.textview3.CanFocus = true;
		this.textview3.Name = "textview3";
		this.textview3.Editable = false;
		this.textview3.CursorVisible = false;
		this.textview3.AcceptsTab = false;
		this.hbox10.Add (this.textview3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.textview3]));
		w14.Position = 1;
		this.hbox8.Add (this.hbox10);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.hbox10]));
		w15.Position = 0;
		// Container child hbox8.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox ();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.image12 = new global::Gtk.Image ();
		this.image12.Name = "image12";
		this.image12.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("NovoMundo.graphics.icons.pepe.png");
		this.hbox13.Add (this.image12);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.image12]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.textview4 = new global::Gtk.TextView ();
		this.textview4.CanFocus = true;
		this.textview4.Name = "textview4";
		this.textview4.Editable = false;
		this.textview4.CursorVisible = false;
		this.textview4.AcceptsTab = false;
		this.hbox13.Add (this.textview4);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.textview4]));
		w17.Position = 1;
		this.hbox8.Add (this.hbox13);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.hbox13]));
		w18.Position = 1;
		this.hbox6.Add (this.hbox8);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.hbox8]));
		w19.Position = 1;
		this.hbox7.Add (this.hbox6);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.hbox6]));
		w20.Position = 0;
		this.hbox5.Add (this.hbox7);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.hbox7]));
		w21.Position = 0;
		this.hbox4.Add (this.hbox5);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.hbox5]));
		w22.Position = 3;
		this.hbox1.Add (this.hbox4);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox4]));
		w23.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vseparator2 = new global::Gtk.VSeparator ();
		this.vseparator2.Name = "vseparator2";
		this.hbox1.Add (this.vseparator2);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vseparator2]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='PresButanToGoction' action='PresButanToGoction'/><toolitem name='SpeedUpSimulation' action='SpeedUpSimulation'/><toolitem name='SlowDownSimulation' action='SlowDownSimulation'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.hbox2.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.toolbar1]));
		w25.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.TimeStatusBar = new global::Gtk.Statusbar ();
		this.TimeStatusBar.WidthRequest = 200;
		this.TimeStatusBar.Name = "TimeStatusBar";
		this.TimeStatusBar.Spacing = 6;
		this.hbox2.Add (this.TimeStatusBar);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.TimeStatusBar]));
		w26.Position = 1;
		this.hbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox2]));
		w27.Position = 2;
		this.vbox8.Add (this.hbox1);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox1]));
		w28.Position = 0;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.OutputBox = new global::Gtk.TextView ();
		this.OutputBox.CanFocus = true;
		this.OutputBox.Name = "OutputBox";
		this.OutputBox.Editable = false;
		this.OutputBox.WrapMode = ((global::Gtk.WrapMode)(3));
		this.GtkScrolledWindow.Add (this.OutputBox);
		this.vbox8.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.GtkScrolledWindow]));
		w30.Position = 1;
		this.vpaned1.Add (this.vbox8);
		global::Gtk.Paned.PanedChild w31 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.vbox8]));
		w31.Resize = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.vbox9 = new global::Gtk.VBox ();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		global::Gtk.Viewport w32 = new global::Gtk.Viewport ();
		w32.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.TileMapEventBox = new global::Gtk.EventBox ();
		this.TileMapEventBox.Name = "TileMapEventBox";
		// Container child TileMapEventBox.Gtk.Container+ContainerChild
		this.TileMap = new global::Gtk.Image ();
		this.TileMap.Name = "TileMap";
		this.TileMap.Xalign = 0F;
		this.TileMapEventBox.Add (this.TileMap);
		w32.Add (this.TileMapEventBox);
		this.GtkScrolledWindow1.Add (w32);
		this.vbox9.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.GtkScrolledWindow1]));
		w36.Position = 0;
		// Container child vbox9.Gtk.Box+BoxChild
		this.StatusBar = new global::Gtk.Statusbar ();
		this.StatusBar.Name = "StatusBar";
		this.StatusBar.Spacing = 6;
		this.vbox9.Add (this.StatusBar);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.StatusBar]));
		w37.Position = 1;
		w37.Expand = false;
		w37.Fill = false;
		this.vpaned1.Add (this.vbox9);
		global::Gtk.Paned.PanedChild w38 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.vbox9]));
		w38.Resize = false;
		w38.Shrink = false;
		this.Add (this.vpaned1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1080;
		this.DefaultHeight = 721;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.quitAction.Activated += new global::System.EventHandler (this.OnQuit);
		this.QuitAction.Activated += new global::System.EventHandler (this.OnQuit);
		this.clearAction.Activated += new global::System.EventHandler (this.OnClearBox);
		this.queryAction.Toggled += new global::System.EventHandler (this.OnQueryButtonToggled);
		this.quitAction1.Activated += new global::System.EventHandler (this.OnQuit);
		this.findAction.Toggled += new global::System.EventHandler (this.OnQueryButtonToggled);
		this.refreshAction1.Activated += new global::System.EventHandler (this.OnClearBox);
		this.PresButanToGoction.Toggled += new global::System.EventHandler (this.OnPresButanToggled);
		this.SpeedUpSimulation.Activated += new global::System.EventHandler (this.OnSpeedUp);
		this.SlowDownSimulation.Activated += new global::System.EventHandler (this.OnSlowDown);
		this.TileMapEventBox.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnTileMapBoxButtonEvent);
	}
}
