
// This file has been generated by the GUI designer. Do not modify.

public partial class QuadrantDialog
{
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView QuadrantTextView;
	
	private global::Gtk.Image QuadrantImage;
	
	private global::Gtk.Notebook notebook3;
	
	private global::Gtk.Label BiotaTab;
	
	private global::Gtk.Label EnergyTab;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Button DeleteMeButton;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget QuadrantDialog
		this.Name = "QuadrantDialog";
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Internal child QuadrantDialog.VBox
		global::Gtk.VBox w1 = this.VBox;
		w1.Name = "dialog1_VBox";
		w1.BorderWidth = ((uint)(2));
		// Container child dialog1_VBox.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.QuadrantTextView = new global::Gtk.TextView ();
		this.QuadrantTextView.CanFocus = true;
		this.QuadrantTextView.Name = "QuadrantTextView";
		this.QuadrantTextView.Editable = false;
		this.QuadrantTextView.CursorVisible = false;
		this.GtkScrolledWindow.Add (this.QuadrantTextView);
		this.hbox5.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.GtkScrolledWindow]));
		w3.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.QuadrantImage = new global::Gtk.Image ();
		this.QuadrantImage.Name = "QuadrantImage";
		this.QuadrantImage.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("NovoMundo.graphics.tiles.civ2tiles.deserthill.png");
		this.hbox5.Add (this.QuadrantImage);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.QuadrantImage]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		w1.Add (this.hbox5);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox5]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child dialog1_VBox.Gtk.Box+BoxChild
		this.notebook3 = new global::Gtk.Notebook ();
		this.notebook3.CanFocus = true;
		this.notebook3.Name = "notebook3";
		this.notebook3.CurrentPage = 0;
		// Notebook tab
		global::Gtk.Label w6 = new global::Gtk.Label ();
		w6.Visible = true;
		this.notebook3.Add (w6);
		this.BiotaTab = new global::Gtk.Label ();
		this.BiotaTab.Name = "BiotaTab";
		this.BiotaTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Biota");
		this.notebook3.SetTabLabel (w6, this.BiotaTab);
		this.BiotaTab.ShowAll ();
		// Notebook tab
		global::Gtk.Label w7 = new global::Gtk.Label ();
		w7.Visible = true;
		this.notebook3.Add (w7);
		this.EnergyTab = new global::Gtk.Label ();
		this.EnergyTab.Name = "EnergyTab";
		this.EnergyTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Energy Flow");
		this.notebook3.SetTabLabel (w7, this.EnergyTab);
		this.EnergyTab.ShowAll ();
		// Notebook tab
		global::Gtk.Label w8 = new global::Gtk.Label ();
		w8.Visible = true;
		this.notebook3.Add (w8);
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("page3");
		this.notebook3.SetTabLabel (w8, this.label5);
		this.label5.ShowAll ();
		// Notebook tab
		global::Gtk.Label w9 = new global::Gtk.Label ();
		w9.Visible = true;
		this.notebook3.Add (w9);
		this.label6 = new global::Gtk.Label ();
		this.label6.Sensitive = false;
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Civilization");
		this.notebook3.SetTabLabel (w9, this.label6);
		this.label6.ShowAll ();
		w1.Add (this.notebook3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(w1 [this.notebook3]));
		w10.PackType = ((global::Gtk.PackType)(1));
		w10.Position = 1;
		// Internal child QuadrantDialog.ActionArea
		global::Gtk.HButtonBox w11 = this.ActionArea;
		w11.Name = "__gtksharp_180_Stetic_TopLevelDialog_ActionArea";
		// Container child __gtksharp_180_Stetic_TopLevelDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
		this.DeleteMeButton = new global::Gtk.Button ();
		this.DeleteMeButton.CanFocus = true;
		this.DeleteMeButton.Name = "DeleteMeButton";
		this.DeleteMeButton.UseUnderline = true;
		this.DeleteMeButton.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.AddActionWidget (this.DeleteMeButton, 0);
		global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w11 [this.DeleteMeButton]));
		w12.Expand = false;
		w12.Fill = false;
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 788;
		this.DefaultHeight = 1002;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteQuadEvent);
	}
}
